# -*- coding: utf-8 -*-
"""WaiterTipPrediction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MAZIaXwHaDii3SoEsEbQNsJywEN1z-2
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as pg
df = pd.read_csv("WaiterTipPredictionDataSet.csv")
print(df.head(5))
#df.groupby["day"].plot.scatter(x = "total_bill", y = "tip").show()
fig = px.scatter(data_frame = df, x="total_bill", y="tip", size="size", color= "day", trendline="ols")#px.scatter(df, x = "total_bill", y="tip", color = "day")
fig.show()

fig = px.scatter(data_frame = df, x="total_bill", y="tip", size="size", color= "sex", trendline="ols")#px.scatter(df, x = "total_bill", y="tip", color = "day")
fig.show()

fig = px.scatter(data_frame = df, x="total_bill", y="tip", size="size", color= "time", trendline="ols")#px.scatter(df, x = "total_bill", y="tip", color = "day")
fig.show()

fig = px.pie(df, names = "day", values= "tip")
fig.show()

fig = px.pie(df, names = "sex", values= "tip")
fig.show()

fig = px.pie(df, names = "smoker", values= "tip")
fig.show()

fig = px.pie(df, names = "time", values= "tip")
fig.show()

dict = {"No": 0, "Yes": 1 , "Thur": 0, "Fri": 1 , "Sat": 2, "Sun": 3, "Male": 0, "Female": 1, "Lunch":0, "Dinner": 1}
df = df.replace({"sex": dict})
df = df.replace({"day": dict})
df= df.replace({"time": dict})
df= df.replace({"smoker": dict})
df.head(5)

from sklearn.model_selection import train_test_split
x = np.array(df[["total_bill", "sex", "smoker", "day","time", "size"]])
y = np.array(df["tip"])
xtraining_data,  xtesting_data, ytraining_data,  ytesting_data = train_test_split(x, y, test_size = 0.2, random_state = 25)
import sklearn.linear_model

from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(xtraining_data, ytraining_data)

#inputs = np.array[["total_bill", "sex", "smoker", "day","time", "size"]]
inputs = np.array([[50, 0, 0, 2, 1, 2]])
model.predict(inputs)